---
abstract: 'The helper for making SQL insert/delete/update statements through a transaction method with a deadlock solution'
author:
  - 'Perlover <perlover@perlover.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-TxnPool
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Try::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Perlover/DBIx-TxnPool.git
version: 0.05
